#doc https://mmistakes.github.io/minimal-mistakes/docs/configuration/

# Basic Info
url: "https://jonsummer.github.io"
baseurl: "" # the subpath of your site, e.g. /blog
title: "Jon Summer's Blog" # the name of your site, e.g. ACME Corp.
title_separator: "|"
name: "Jon Summer"
description: "A Blog for Jon Summer"
repository: "jonsummer/jonsummer.github.io"

# Theme
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
locale: "zh-CN" #"en-US"
timezone: "Asia/Shanghai"
words_per_minute: 250

# Default Config
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author: Jon Summer
      author_profile: true
      read_time: true
      share: false
      related: true
      show_date: true
      comments: false
      sidebar:
        nav: "posts"
      toc: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      author_profile: true

#permalink: /:categories/:year/:month/:day/:title/
#permalink: pretty
permalink: /:categories/:title/


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/
  recipes:
    output: false
    permalink: /:collection/:path/
  pets:
    output: false
    permalink: /:collection/:path/
  portfolio:
    output: false
    permalink: /:collection/:path/

comments:
  provider: "false"
  utterances:
    theme: "github-dark" # "github-dark"
    issue_term: "pathname"


head_scripts:
  #- https://code.jquery.com/jquery-3.2.1.min.js

teaser: "/assets/images/500x300.png"
logo: "/assets/images/88x88.png"
breadcrumbs: true
breadcrumb_home_label : "Home"
breadcrumb_separator  : "|"

search: true
search_full_content      : true


footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "http://github.com/jonsummer/"
    - label: "Terms"
      url: /terms/
    - label: "Sitemap"
      url: /sitemap/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

include:
  - .htaccess
  - _pages

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Makefile
  - .vscode/

keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

compress_html:
  clippings: all
  ignore:
    envs: development  # disable compression in dev environment